%% Search for a specified operating point for the model - X8_trim.
%
% This MATLAB script is the command line equivalent of the trim model
% tab in linear analysis tool with current specifications and options.
% It produces the exact same operating points as hitting the Trim button.

% MATLAB(R) file generated by MATLAB(R) 9.5 and Simulink Control Design (TM) 5.2.
%
% Generated on: 17-Dec-2019 14:35:33

%% Specify the model name
model = 'X8_trim';

%% Create the operating point specification object.
opspec = operspec(model);

%% Set the constraints on the states in the model.
% - The defaults for all states are Known = false, SteadyState = true,
%   Min = -Inf, Max = Inf, dxMin = -Inf, and dxMax = Inf.

% State (1) - X8_trim/Subsystem/Dynamics1/Integrator
quat0 = euler2q(0,0,pi/2);
Va = 20;
AoA = 4;
opspec.States(1).SteadyState = [0;0;1;0;0;0;0;1;1;1;1;1;1];
opspec.States(1).Known = [0;0;1;0;0;0;0;0;0;0;1;1;1];
opspec.States(1).x = [0;0;-50;quat0;Va*cosd(AoA);0;Va*sind(AoA);0;0;0];

% State (2) - X8_trim/Subsystem/Forces/Calculate Control Parameters/Unit Delay1
% - Default model initial conditions are used to initialize optimization.

% State (3) - X8_trim/Subsystem/Forces/Calculate Control Parameters/Unit Delay2
% - Default model initial conditions are used to initialize optimization.

% State (4) - X8_trim/Subsystem/Forces/Calculate Control Parameters/Unit Delay3
% - Default model initial conditions are used to initialize optimization.

% State (5) - X8_trim/Subsystem/Forces/Calculate Control Parameters/Unit Delay4
% - Default model initial conditions are used to initialize optimization.
% opspec.States(5).Known = true;
% opspec.States(5).Min = 0;
% opspec.States(5).Max = 1;

%% Set the constraints on the inputs in the model.
% - The defaults for all inputs are Known = false, Min = -Inf, and
% Max = Inf.

% Input (1) - X8_trim/delta_e
% - Default model initial conditions are used to initialize optimization.
opspec.Inputs(1).Max = P.aileronMax;
opspec.Inputs(1).Min = P.aileronMin;
opspec.Inputs(1).u = 0;
% Input (2) - X8_trim/delta_a
% - Default model initial conditions are used to initialize optimization.
opspec.Inputs(2).Max = P.aileronMax;
opspec.Inputs(2).Min = P.aileronMin;
% Input (3) - X8_trim/delta_r
% - Default model initial conditions are used to initialize optimization.
opspec.Inputs(3).Max = 0;
opspec.Inputs(3).Min = 0;
% Input (4) - X8_trim/delta_t
% - Default model initial conditions are used to initialize optimization.
opspec.Inputs(4).Max = 1;
opspec.Inputs(4).Min = 0;
opspec.Inputs(4).u = 0.5;
%% Set the constraints on the outputs in the model.
% - The defaults for all outputs are Known = false, Min = -Inf, and
% Max = Inf.

% Output (1) - X8_trim/Va
% - Default model initial conditions are used to initialize optimization.
opspec.Outputs(1).Known  = 1;
opspec.Outputs(1).y = Va;
% Output (2) - X8_trim/alpha
% - Default model initial conditions are used to initialize optimization.
opspec.Outputs(2).y = deg2rad(AoA);

% Output (3) - X8_trim/beta
% - Default model initial conditions are used to initialize optimization.
opspec.Outputs(3).Known  = 0;
opspec.Outputs(3).y = 0;
% Output (4) - X8_trim/eta
% - Default model initial conditions are used to initialize optimization.
opspec.Outputs(4).Known = [0;0;0;0;0;0;0];
opspec.Outputs(4).y = [0;0;0;quat0];
% Output (5) - X8_trim/ny
% - Default model initial conditions are used to initialize optimization.
opspec.Outputs(5).Known = [0;0;0;0;0;0];
opspec.Outputs(5).y = [Va;0;0;0;0;0];
% Output (6) - X8_trim/euler
% - Default model initial conditions are used to initialize optimization.
opspec.Outputs(6).Known = [0;0;0];
opspec.Outputs(6).y = [0;0;0];

opspec.Outputs(7).Known = [0;0;0;0;0;0];
opspec.Outputs(7).y = [0;0;0;0;0;0];
%% Create the options
opt = findopOptions('DisplayReport','iter');
opt.OptimizationOptions.MaxFunEvals = 10000;
%% Perform the operating point search.
[op,opreport] = findop(model,opspec,opt);

X_trim = op.States(1).x;
U_trim = [op.Inputs(1).u;op.Inputs(2).u;op.Inputs(3).u;op.Inputs(4).u];
X_trim = [X_trim;op.Inputs(1).u;0;-op.Inputs(1).u;0;op.Inputs(4).u];
x0 = X_trim;
